### PR TITLE
updated 600px responsiveness on CSS

### PR DESCRIPTION
**Pull request by April00h**

### CODE REVIEW

**Review by April00h — COMMENTED** [review]
Updated final information 

Things not fixed -Image results of cards not put into a row and stats not moved into a column

**Comment by RugbyVeronica** [comment]
Checked and approved, thank you

**Comment by RugbyVeronica** [comment]
Checked and approved

**Comment by RugbyVeronica** [comment]
Reopening for approval

**Review by RugbyVeronica — APPROVED** [review]
Checked and approved. 👍🏼

**Pull request merged**
